pod "libjingle_peerconnection"
pod "Primus", :git => 'git@github.com:cine-io/primus-objc.git', :commit => '8f63ae63d7f974655a5b22a5ee967e2b54050ba5'
pod "SocketRocket", "= 0.3.1-beta2"

# Add this to the bottom so it won't have issues with active architecture
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = ['armv7', 'armv7s']
        end
    end
end
