pod "libjingle_peerconnection"
pod "Primus"
pod "SocketRocket", "= 0.3.1-beta2"

# Add this to the bottom so it won't have issues with active architecture
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['VALID_ARCHS'] = ['armv7', 'armv7s']
        end
    end
end
